name: Module CI/CD

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Get Version
        shell: bash
        id: get-version
        run: echo "::set-output name=version::$(node ./.github/workflows/get-version.js)"

      - name: Install dependencies
        run: npm install

      - name: Build Production
        run: npm run build:production

      - name: Create installable module zip file
        shell: bash
        working-directory: ./dist
        run: zip -r ../womboras-journal-helper.zip *

      # Update the 'latest' release
      - name: Update Latest Release
        id: create_latest_release
        uses: ncipollo/release-action@v1
        if: endsWith(github.ref, 'master')
        with:
          allowUpdates: true
          name: Latest
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: './module/module.json, ./womboras-journal-helper.zip'
          tag: latest

      # Create a release for this specific version
      - name: Create Version Release
        id: create_version_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true # set this to false if you want to prevent updating existing releases
          name: Release ${{ steps.get-version.outputs.version }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: './module/module.json,./womboras-journal-helper.zip'
          tag: ${{ steps.get-version.outputs.version }}
